title: César Domínguez
logo: /assets/img/head.JPG
description: Catedrático de Literatura comparada [LinkedIn](https://www.linkedin.com/in/paulo-dom%C3%ADnguez-l%C3%B3pez-26b883255/) @ USC [LinkedIn](https://www.linkedin.com/in/paulo-dom%C3%ADnguez-l%C3%B3pez-26b883255/) · [Honorary Research Fellow] (https://www.gla.ac.uk/schools/mlc/staff/index.html/staffcontact/person/4edeeaec8092) @ [U of Glasgow](https://www.gla.ac.uk/)
show_downloads: false
theme: jekyll-theme-minimal
